version: 2
jobs:
  setup:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: [.]

  modtidyvendor:
    docker:
      - image: golang:1.13
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Check modules are tidy
          command: |
            go mod tidy
            if [ "$(git status --porcelain)" != "" ]; then
              echo "git tree is dirty after tidying"
              echo "ensure go.mod and go.sum are tidy"
              git status
              exit 1
            fi

  test:
    docker:
      - image: golang:1.13
    steps:
      - attach_workspace: { at: . }
      - run: go mod test -mod=readonly -v ./...

  vet:
    docker:
      - image: golang:1.13
    steps:
      - attach_workspace: { at: . }
      - run: go vet -mod=readonly ./...

  build:
    docker:
      - image: golang:1.13
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Build
          command: |
            make build

workflows:
  version: 2
  run:
    jobs:
      - setup
      - modtidyvendor:
          requires: [setup]
      - test:
          requires: [setup]
      - vet:
          requires: [setup]
      - build:
          requires: [setup]
