version: 2
jobs:
  modtidy:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run:
          name: Check modules are tidy
          command: |
            go mod tidy
            if [ "$(git status --porcelain)" != "" ]; then
              echo "git tree is dirty after tidying"
              echo "ensure go.mod and go.sum are tidy"
              git status
              exit 1
            fi

  test:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run: go test -mod=readonly -v ./...

  vet:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run: go vet -mod=readonly ./...

  build:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run:
          name: Build
          command: |
            make build

workflows:
  version: 2
  run:
    jobs:
      - modtidy
      - test
      - vet
      - build
