version: 2
jobs:
  setup:
    resource_class: small
    docker:
      - image: segment/circleci-golang:1.12
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: [.]

  modtidyvendor:
    resource_class: small
    docker:
      - image: segment/circleci-golang:1.12
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Check modules are tidy and checked in
          command: |
            export GO111MODULE=on
            go mod tidy
            go mod vendor
            if [ "$(git status --porcelain)" != "" ]; then
              echo "git tree is dirty after tidying and vendoring modules"
              echo "ensure go.mod and go.sum are tidy and vendor is checked in"
              git status
              exit 1
            fi

  test:
    resource_class: small
    docker:
      - image: segment/circleci-golang:1.12
    steps:
      - attach_workspace: { at: . }
      - run: make test

  vet:
    resource_class: small
    docker:
      - image: segment/circleci-golang:1.12
    steps:
      - attach_workspace: { at: . }
      - run: make lint

  build:
    docker:
      - image: segment/circleci-golang:1.12
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Build
          command: |
            make build
      - persist_to_workspace:
          root: .
          paths: [./dist/]


  publish:
    working_directory: /go/src/github.com/segmentio/robo
    docker:
      - image: segment/circleci-golang:1.10
    steps:
      - attach_workspace: { at: . }
      - setup_remote_docker: { reusable: true }
      - run:
          name: Release
          command: |
            make release

workflows:
  version: 2
  run:
    jobs:
      - setup:
          filters:
            tags: { only: /.*/ }
      - modtidyvendor:
          requires: [setup]
      - test:
          requires: [setup]
      - vet:
          requires: [setup]
      - build:
          requires: [setup]
          filters:
            tags: { only: /.*/ }
      - publish:
          requires: [build]
          filters:
            tags: { only: /.*/ }
            branches: { ignore: /.*/ }
